---
title: "babynames"
author: "Yasser Mushtaq"
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
# packages 
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, fig.showtext = TRUE)
library(tidyverse)
library(ggwordcloud)
library(patchwork)
library(ggtext)
extrafont::loadfonts()
```

```{r data}
# load babyname data
tuesdata <- tidytuesdayR::tt_load('2022-03-22')
babynames <- tuesdata$babynames

head(babynames)
```


```{r}
#explore data
babynames %>%
  group_by(year) %>%
  summarise(
    total = sum(n)
  ) %>%
  ggplot(aes(x = year, y = total)) +
  geom_area()

# will select the following years to plot (seems like a good spread!)
years <- c("1920", "1950", "1980", "2010", "2017")
```


```{r, fig.showtext=TRUE}
# loop through years above and assign word cloud
# set seed as this fixes the points at which the function plots the names (without this, plots look different at each execution)
set.seed(42)

for (y in years) {
  plot <-
    babynames %>%
      filter(year == y) %>%
      arrange(desc(prop)) %>%
      head(50) %>%
      ggplot(aes(label = name, size = prop, colour = sex)) +
      geom_text_wordcloud(shape = "circle", family = "Unna") +
      #scale_size_area(max_size = 5) +
      scale_radius(range = c(0, 10), limits = c(0, NA)) +
      labs(title = y) +
      theme_minimal() +
      theme(
        plot.title = element_text(family = "Unna", size = 18, hjust = 0.5),
        plot.title.position = "plot"
      )
  
  assign(paste0("names",y), plot)
}

# check individual plots...
names1920
names1950
names1980
names2010
names2017
```


```{r, fig.showtext=TRUE}}
# final figure, using Patchwork layout
# sometimes throws an error about words not fitting on page - this seems just to relate to the console view
# seems fine in png file, or when zooming in
names1920 / names1950 / names1980 / names2017 +
  plot_layout(heights = c(20, 20, 20, 40), widths = c(20, 20)) +
  plot_annotation(
  title = 'Baby Name Diversity - A Comparison Overtime',
  subtitle = 'Each cloud showing top 50 names that year, as a proportion of total births (USA data)',
  caption = 'In 1920, a small number of names made up a significant proportion.<br>
             There is greater diversity in 2017.<br> 
             Data - babynames package | Chart by @Yass3r',
  theme = 
  theme(
    plot.title = element_markdown(color = "grey10", size = 14, face = "bold",
                                margin = margin(t = 15)),
    plot.subtitle = element_markdown(color = "grey30", size = 12, 
                                   lineheight = 1.35,
                                   margin = margin(t = 15, b = 40)),
    plot.title.position = "plot",
    plot.caption.position = "plot",
    text = element_text(family = "Roboto Condensed"),
    plot.caption = element_markdown(color = "grey30", size = 10,
                              lineheight = 1.2, hjust = 0)
  ))

ggsave(filename = "babynames-wordcloud.png",
         width = 21, 
         height = 29.7, 
         units = "cm",
         device = ragg::agg_png,
         dpi = 320)
```


```{r}
# tables for reference/checking

for (y in years) {
  names_table <-
    babynames %>%
      filter(year == y) %>%
      arrange(desc(prop)) %>%
      head(50)
  
  assign(paste0("table", y), names_table)
  
}

```

