---
title: "cran"
author: "Yasser Mushtaq"
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)
library(lubridate)
library(ggtext)
library(grid)
library(viridis)
library(patchwork)
extrafont::loadfonts()

cran <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2022/2022-03-15/cran.csv')

cran <- cran %>%
  mutate(date = case_when(grepl("^[[:digit:]]",date) ~ as.Date(date), 
                          TRUE ~ as.Date(substr(date,5,nchar(date)), '%b %d %H:%M:%S %Y')),
         yearmonth = ym(format(date, "%Y-%m")))

vignette_summary <- cran %>%
  group_by(yearmonth) %>%
  summarise(
    total_rnw = sum(rnw),
    total_rmd = sum(rmd), .groups = 'drop'
  ) %>%
  filter(yearmonth %within% interval(ymd("2011-10-01"), ymd("2021-09-01"))) %>%
  mutate(totalvignette = total_rnw + total_rmd,
         perc_rnw = round(total_rnw / totalvignette, 2),
         perc_rmd = round(total_rmd / totalvignette, 2))

```


```{r}
# some labels to include in the chart
rmd_vignette_intro <- ymd("2013-04-01")

label_r_3 <- textGrob("R 3.0.0 introduces vignette\n creation by engines besides\n Sweave", gp=gpar(fontsize = 8, family = "Roboto Condensed"))

ggplot_first_vig <- cran %>%
  mutate(totalvignette = rnw + rmd) %>%
  filter(package == "ggplot2", totalvignette > 0) %>%
  select(date) %>%
  slice(1) %>%
  pull()

dplyr_first_vig <- cran %>%
  mutate(totalvignette = rnw + rmd) %>%
  filter(package == "dplyr", totalvignette > 0) %>%
  select(date) %>%
  slice(1) %>%
  pull()

stringr_first_vig <- cran %>%
  mutate(totalvignette = rnw + rmd) %>%
  filter(package == "stringr", totalvignette > 0) %>%
  select(date) %>%
  slice(1) %>%
  pull()

# get logos
get_png <- function(filename, width = 1) {
  grid::rasterGrob(png::readPNG(filename), interpolate = TRUE, width = width)
}

# in local directory
l_md <- get_png("rmarkdown.png")
l_ggplot <- get_png("ggplot2.png")
l_dplyr <- get_png("dplyr.png")
l_stringr <- get_png("stringr.png")
```


```{r, fig.showtext=TRUE}
# plot
# set general theme for all plots
theme_update(
  axis.title = element_blank(),
  axis.text = element_text(color = "grey40"),
  axis.text.x = element_text(size = 12, margin = margin(t = 5)),
  axis.text.y = element_text(size = 12, margin = margin(r = 5)),
  axis.ticks = element_line(color = "grey91", size = .5),
  axis.ticks.length.x = unit(.7, "lines"),
  axis.ticks.length.y = unit(.7, "lines"),
  panel.grid = element_blank(),
  plot.margin = margin(10, 50, 30, 10),
  plot.background = element_rect(fill = "grey98", color = "grey98"),
  panel.background = element_rect(fill = "grey98", color = "grey98"),
  plot.title = element_markdown(color = "grey10", size = 14, face = "bold",
                                margin = margin(t = 15)),
  plot.subtitle = element_markdown(color = "grey30", size = 12, 
                                   lineheight = 1.35,
                                   margin = margin(t = 15, b = 40)),
  plot.title.position = "plot",
  plot.caption.position = "plot",
  text = element_text(family = "Roboto Condensed"),
  plot.caption = element_markdown(color = "grey30", size = 10,
                              lineheight = 1.2, hjust = 0)
)
# step chart showing % rmd and sweave
fig1 <- ggplot(vignette_summary) +
  geom_step(aes(x = yearmonth, y = perc_rnw), color = "#6C5B7B") +
  geom_step(aes(x = yearmonth, y = perc_rmd), color = "#F8B195") +
  geom_segment(
    data = tibble(y = seq(0, 1, by = 0.25), x1 = ymd("2011-10-01"), x2 = ymd("2021-09-01")),
    aes(x = x1, xend = x2, y = y, yend = y),
    inherit.aes = FALSE,
    color = "grey91",
    size = .3,
    alpha = .5
  ) +
  annotation_custom(l_md, xmin = ymd("2021-10-01"), xmax = ymd("2022-04-01"), ymin = 0.95, ymax = 1) +
  annotate(
    geom = "richtext",
    x = ymd("2022-02-01"),
    y = 0.03,
    label = "**Sweave**",
    color = "#4f1f10", family = "Fredoka",
    fill = NA, label.color = NA, size = 5
  ) +
  annotation_custom(label_r_3,xmin = rmd_vignette_intro, xmax = rmd_vignette_intro, ymin = -0.185, ymax = -0.185) +
  annotation_custom(l_dplyr,xmin = dplyr_first_vig, xmax = dplyr_first_vig +120, ymin = -0.17, ymax = -0.20) +
  annotation_custom(l_ggplot,xmin = ggplot_first_vig, xmax = ggplot_first_vig +120, ymin = -0.17, ymax = -0.20) +
  annotation_custom(l_stringr,xmin = stringr_first_vig, xmax = stringr_first_vig +120, ymin = -0.17, ymax = -0.20) +
  geom_segment(aes(x = rmd_vignette_intro, xend = rmd_vignette_intro, y = -0.13, yend = 0), linetype = "dashed", alpha = .5, size = 0.1) +
  geom_segment(aes(x = dplyr_first_vig, xend = dplyr_first_vig, y = -0.17, yend = 0), linetype = "dashed", alpha = .5, size = 0.1) +
  geom_segment(aes(x = ggplot_first_vig, xend = ggplot_first_vig, y = -0.17, yend = 0), linetype = "dashed", alpha = .5, size = 0.1) +
  geom_segment(aes(x = stringr_first_vig, xend = stringr_first_vig, y = -0.17, yend = 0), linetype = "dashed", alpha = .5, size = 0.1) +
  scale_y_continuous(labels = scales::percent) +
  coord_cartesian(ylim = c(0, 1), clip="off") +
  labs(title = "Percentage of Total Vignettes Created by <span style='color:#4f1f10'>**Sweave**</span> and <span style='color:#4f1f10'>**R Markdown**</span>",
       subtitle = "Percentage of total vignettes composed by Sweave and R Markdown aggregated by year-month, followed by<br>total number of
                    vignettes uploaded to CRAN")


# tile chart showing total counts
fig2 <- ggplot(vignette_summary, aes(x = yearmonth, y = 0, fill = totalvignette)) +
  geom_tile(colour = "gray50", linetype = 3, height=.9) +  # changed from linetype 1
  labs(x = "", y = "", fill = "Total Vignettes",
       caption = "Highlighted on the x-axis are the first point at which RMD vignettes were introduced<br>
                  and first RMD vignettes uploaded for selected Tidyverse packages<br>
                  Data - Robert Flight | Chart by @Yass3r") +
  #scale_y_discrete(expand=c(0,0)) +
  scale_fill_viridis_c(direction = -1) +
  coord_fixed(ratio = 100, clip = "off") +
  theme(legend.position = "bottom",
        legend.key.height= unit(0.3, 'cm'),
        plot.margin = margin(10, 10, 0, 10),
        axis.text.x = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks = element_blank(),
        panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank(),
        legend.background = element_rect(fill = "grey98", color = "grey98"),
        legend.text = element_text(size=10, family = "Roboto Condensed"),
        legend.title = element_text(size = 10, family = "Roboto Condensed", vjust = 1))

#fig2
```

```{r, fig.showtext=TRUE}
# compile figure and save
fig1 / fig2 +
  plot_layout(heights = c(40, 3), widths = c(20, 20))

ggsave(filename = "cran-vignettes.png",
         width = 35, 
         height = 25, 
         units = "cm",
         device = ragg::agg_png,
         dpi = 320)
```


