---
title: "Kaggle-Hidden-Gems"
author: "Yasser Mushtaq"
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggtext)
extrafont::loadfonts()

tuesdata <- tidytuesdayR::tt_load(2022, week = 17)
hidden_gems <- tuesdata$hidden_gems

# seems to be quite a few mentions of EDA - exploratory data analysis
sum(str_detect(hidden_gems$title, "EDA"))

sum(str_detect(hidden_gems$review, "EDA"))


hidden_gems %>%
  mutate(
    # detetct the presence of "EDA" in either the title or review
    EDA = 
      case_when(
        str_detect(title, "EDA") ~ TRUE,
        str_detect(review, "EDA") ~ TRUE,
        TRUE ~ FALSE
      )) %>%
  select(vol, date, title, review, EDA) %>%
  # number of EDA notebooks per volume
  group_by(vol) %>%
  mutate(
    EDA_count = sum(EDA)
  ) %>%
  ungroup() -> EDA_detect

# plot data
EDA_detect %>%
  select(vol, date, EDA_count) %>%
  unique() -> EDA_plot

# for categorical colour scale
EDA_plot$EDA_count <- as.factor(EDA_plot$EDA_count)

# add reference for plotting separate segments
EDA_plot %>%
  mutate(
    plot_seg =
      case_when(
        between(vol, 1, 20) ~ 1,
        between(vol, 21, 40) ~ 2,
        between(vol, 41, 60) ~ 3,
        between(vol, 61, 80) ~ 4,
        between(vol, 81, 100) ~ 5,
      ),
    x = rep(0:19, 5)
  ) -> EDA_plot
```


```{r}
# labels for plot
labels <- tibble(
  x = 0,
  y = 1:5,
  text = c("Vol 1", "Vol 21", "Vol 41", "Vol 61", "Vol 81")
)

# plot
ggplot() +
  geom_segment(data = EDA_plot, aes(x = x + .5, xend = x + (.5+.9), y = plot_seg, yend = plot_seg, color = EDA_count),
               size = 3) +
  geom_segment(aes(x = 0 + .5, xend = 2 + (.5+.9), y = 1 - .4, yend = 1 - .4),
               size = 0.5, color = "white",
               arrow = arrow(length = unit(0.005, "npc"))) +
  geom_text(data = labels, aes(x = x, y = y, label = text), colour = "white", family = "Literata", fontface = "bold") +
  annotate(
    geom = "richtext",
    x = 0,
    y = -6,
    label = "**Searching for EDA <br> in Kaggle Hidden Gems**",
    color = "white", family = "Literata",
    fill = NA, label.color = NA, size = 7
  ) +
  scale_color_manual(values = c("#D4D3D2", "#52635d", "#817141")) +
  ylim(-7, 6) +
  xlim(0, 21.5) +
  coord_polar() +
  labs(
    colour = "Count per volume of notebooks with EDA reference",
    caption = "Count of EDA references in notebook title or review - each volume consists of three notebooks <br> 
               EDA - Exploratory Data Analysis | Chart by @Yass3r | Data by Martin Henze (Heads or Tails) @heads0rtai1s"
  ) +
  guides(color = guide_legend(keywidth = 10, keyheight = 2, title.position = "top",
                              title.hjust = .5)) +
  theme(
    panel.grid = element_blank(),
    axis.ticks = element_blank(),
    axis.text = element_blank(),
    axis.title = element_blank(),
    legend.position = "bottom",
    legend.key = element_blank(),
    legend.key.width = unit(20, "mm"),
    legend.text = element_text(family = "Literata", hjust = 0.5, size = 10, colour = "white", face = "bold"),
    legend.title = element_text(family = "Literata",size = 14, colour = "white", face = "bold"),
    legend.direction = "horizontal",
    legend.background = element_rect(fill = "#393939"),
    panel.background = element_rect(fill = "#393939", colour = "#393939"),
    plot.background = element_rect(fill = "#393939", colour = "black", size = 3),
    plot.caption = element_markdown(family = "Literata", color = "white", size = 8, lineheight = 1.2, hjust = 0.5)
  )

# save

ggsave(filename = "kaggle-hidden-gems.png",
         width = 20, 
         height = 24, 
         units = "cm",
         device = ragg::agg_png,
         dpi = 320)
```

