---
title: "Indoor-Air-Pollution-Final"
author: "Yasser Mushtaq"
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggtext)
library(ggrepel)
extrafont::loadfonts()
tuesdata <- tidytuesdayR::tt_load('2022-04-12')
tuesdata <- tidytuesdayR::tt_load(2022, week = 15)

indoor_pollution <- tuesdata$indoor_pollution
```

```{r}
# fonts, colours
colup <- MetBrewer::met.brewer("Cross")[2]
coldown <- MetBrewer::met.brewer("Archambault")[1]
ft <- "Avenir Next Condensed"
ft_2 <- "Crete Round"

```

```{r}
# data wrangling
indoor_pollution %>%
  janitor::clean_names() %>%
  rename(deaths_indoor_pollution_perc =      deaths_cause_all_causes_risk_household_air_pollution_from_solid_fuels_sex_both_age_age_standardized_percent) -> indoor_pollution

indoor_pollution %>%
  filter(year %in% c("1990", "2019"), !is.na(code)) %>%
  pivot_wider(names_from = year, values_from = deaths_indoor_pollution_perc, names_prefix = "y") %>%
  mutate(perc_change = y2019 - y1990) -> perc_change

perc_change %>%
  slice_min(order_by = perc_change, n = 5) -> top_5_dec

perc_change %>%
  slice_max(order_by = perc_change, n = 3) -> perc_incr

indoor_pollution %>%
  filter(year %in% c("1990", "2019"), !is.na(code)) %>%
  # background data
  filter(!entity %in% top_10_dec$entity, !entity %in% perc_incr$entity) -> background_data

indoor_pollution %>%
  filter(year %in% c("1990", "2019"), !is.na(code)) %>%
  # top 10 decrease 
  filter(entity %in% top_5_dec$entity) -> top_5_dec_plot
# for plot labels...  
top_5_dec_plot %>%
  mutate(hjust = if_else(year == 2019, -1, 2)) -> top_5_dec_plot

indoor_pollution %>%
  filter(year %in% c("1990", "2019"), !is.na(code)) %>%
  # top 10 decrease 
  filter(entity %in% perc_incr$entity) -> perc_incr_plot

# SDI data
indoor_pollution %>%
  filter(year %in% c("1990", "2019"), entity %in% c("High SDI", "Low SDI", "Middle SDI")) -> SDI_data

#SDI labels
SDI_data %>%
  filter(entity == "High SDI" & year == 1990 |
         entity == "Middle SDI" & year == 2019 |
         entity == "Low SDI" & year == 2019) %>%
  mutate(hjust = c(2, -1, 2)) -> SDI_data_labels
```

```{r}
p <- ggplot() +
  geom_line(data = background_data, aes(x = year, y = deaths_indoor_pollution_perc, group = entity), colour = "#f5f3f0") +
  geom_line(data = perc_incr_plot, aes(x = year, y = deaths_indoor_pollution_perc, group = entity), colour = colup) + # #BF091C
  geom_line(data = top_5_dec_plot, aes(x = year, y = deaths_indoor_pollution_perc, group = entity), colour = coldown) +
  geom_line(data = SDI_data, aes(x = year, y = deaths_indoor_pollution_perc, group = entity), colour = "#06DD6E", alpha = 0.5,
                           linetype = "dashed", size = 1) +
  geom_text_repel(data = top_5_dec_plot, aes(label = entity, x = year, y = deaths_indoor_pollution_perc),
                  #xlim = c(1986, 2023.5),
                  family = ft,
                  hjust = top_5_dec_plot$hjust,
                  min.segment.length = 0,
                  direction = "y",
                  segment.size = .7,
                  segment.alpha = .5,
                  segment.linetype = "dotted",
                  box.padding = .4,
                  segment.curvature = -0.1,
                  segment.ncp = 3,
                  segment.angle = 20) +
  geom_text_repel(data = subset(perc_incr_plot, year == 2019), aes(label = entity, x = year, y = deaths_indoor_pollution_perc),
                  family = ft, 
                  hjust = -1,
                  min.segment.length = 0,
                  direction = "y",
                  segment.size = .7,
                  segment.alpha = .5,
                  segment.linetype = "dotted",
                  box.padding = .4,
                  segment.curvature = -0.1,
                  segment.ncp = 3,
                  segment.angle = 20) +
  geom_text_repel(data = SDI_data_labels, aes(label = entity, x = year, y = deaths_indoor_pollution_perc),
                  family = ft,
                  hjust = SDI_data_labels$hjust,
                  nudge_y = 0.2,
                  min.segment.length = 0,
                  direction = "y",
                  segment.size = .7,
                  segment.alpha = .5,
                  segment.linetype = "dotted",
                  box.padding = .4,
                  segment.curvature = -0.1,
                  segment.ncp = 3,
                  segment.angle = 20) +
  scale_x_continuous(
    expand = c(0, 0),
    limits = c(1986, 2023.5), 
    breaks = c(1990, 2019),
    position = "top") +
  scale_y_continuous(labels = function(x) paste(x, "%")) +
  labs(
    title = title,
    subtitle = subtitle,
    caption = caption,
    x = NULL,
    y = "% Deaths Attributed to Indoor Pollution"
  ) +
  theme_minimal(base_family = ft_2) +
  theme(
    panel.grid = element_blank(),
    axis.text = element_text(size = 12),
    axis.title.y = element_text(size = 12),
    plot.background = element_rect(fill = "#efe8d1", color = "#efe8d1"), 
    panel.background = element_rect(fill = "#efe8d1", color = "#efe8d1"),
    plot.title = element_markdown(color = "grey10", size = 16, face = "bold",
                                margin = margin(t = 15)),
    plot.subtitle = element_markdown(color = "grey30", size = 10, 
                                   lineheight = 1.35,
                                   margin = margin(t = 15, b = 40),),
    plot.caption = element_markdown(color = "grey30", size = 10,
                              lineheight = 1.2, hjust = 0)
  )

ggsave(filename = "indoor-air-pollution.png",
         width = 20, 
         height = 24, 
         units = "cm",
         device = ragg::agg_png,
         dpi = 320)
```

